https://api.magicthegathering.io/v1/cards

###
https://api.magicthegathering.io/v1/cards/758df5d5-992f-5d30-b6bc-87cb1a0788ab


###
http://localhost:8080/api/cards/all

###
http://localhost:8080/api/cards?phrase=mage%20alabaster%20dragon&color=Red

###
http://localhost:8080/api/cards?id=758df5d5-992f-5d30-b6bc-87cb1a0788ab,aeb1b742-645c-5dab-ba9b-35d51649e074

###
http://localhost:8080/api/cards/aeb1b742-645c-5dab-ba9b-35d51649e074

###
http://localhost:8080/api/cards?phrase=Black%20Lotus


###
http://localhost:8080/api/cards/b2c955c0-7f0b-5748-ab5d-98af82d8c682


###
http://localhost:8080/api/cards/758df5d5-992f-5d30-b6bc-87cb1a0788ab,e4b4684b-8e14-5fcf-9286-497b7afd5b3a,aeb1b742-645c-5dab-ba9b-35d51649e074


###
http://localhost:8080/api/types

###
http://localhost:8080/api/sets

###
http://localhost:8081/api/formats

###
http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129465&type=card


###
http://localhost:8080/api/cards?sortBy=toughness&formats=Historicbrawl,Future,Penny,Gladiator,Alchemy,Vintage

###
http://localhost:8081/api/cards/internal/ids