server:
  port: 9000
spring:
  application:
    name: user-service
  datasource:
    username: postgres
    password: password
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/users}
  jpa:
    generate-ddl: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


environments:
  jwt:
    token:
      secret: secret
      time: 10 #in minutes



