on:
  push:
    branches:
    - master
    - github-action
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: ./mtb-frontend
            image: ghcr.io/jakubk/mtb-frontend:latest
          - context: ./api-gateway
            image: ghcr.io/jakubk/mtb-api-gateway:latest
          - context: ./card-service
            image: ghcr.io/jakubk/mtb-card-service:latest
          - context: ./deck-service
            image: ghcr.io/jakubk/mtb-deck-service:latest
          - context: ./user-service
            image: ghcr.io/jakubk/mtb-user-service:latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PACKAGE_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ${{ matrix.image }}